/*
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"

Example 3:
Input: s = "a", t = "aa"
Output: "a"

Example 4:
Input: s = "ae", t = "aea"
Output: "a"

Constraints:
0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lower-case English letters.

*/
class Solution {
    public char findTheDifference(String s, String t) 
    {
        char ch = 'a' ;
        int arr[] = new int[26];
        
        for(int i = 0; i < s.length(); i++)
        {
            arr[s.charAt(i) - 'a']++;
        }
        
        for(int i = 0; i < t.length(); i++)
        {
            arr[t.charAt(i) - 'a']++;
        }
        
        for(int i = 0; i < 26; i++)
        {
            if(arr[i] % 2 != 0)
            {
                break;
            }    
            ch++;
                
        }
        //System.out.println("ch "+ch);
        
        return ch;
    }
}
